version: '3.9'

services:
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - database-data:/var/lib/mysql
    networks:
      - recipe-network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - recipe-network

volumes:
  database-data:

networks:
  recipe-network: