name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: PHPUnit tests
        run: ./vendor/bin/phpunit tests/Unit

  functional_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP and database
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Create or update test database
        run: php bin/console doctrine:database:create --if-not-exists --env=test

      - name: Migrate test database
        run: php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Load fixtures
        run: vendor/bin/doctrine fixtures:load --append

      - name: Run functional tests
        run: vendor/bin/phpunit tests/Functional

      - name: Stop Docker Compose
        run: docker-compose down -v