name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: PHPUnit tests
        run: ./vendor/bin/phpunit tests/Unit

  functional_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        uses: docker/bake-action@v3
        with:
          pull: true
          load: true
          files: |
            docker-compose.yml
            docker-compose.override.yml

      - name: Start Docker Compose
        run: docker compose up --wait --no-build

#      - name: Install dependencies
#        run: docker-compose exec -T php composer install --no-interaction

      - name: Create or update test database
        run:  docker compose exec -T php bin/console -e test doctrine:database:create

      - name: Migrate test database
        run: docker compose exec -T php bin/console -e test doctrine:migrations:migrate --no-interaction

      - name: Load fixtures
        run: docker-compose exec -T php vendor/bin/doctrine fixtures:load

      - name: Run functional tests
        run: docker-compose exec -T php vendor/bin/phpunit tests/Functional

      - name: Stop Docker Compose
        run: docker-compose down -v
